### ISSUE TITLE
Modify Lesson 4 content for clarity

### ISSUE THREAD

**Issue by vcgalpin** [links-lang/links-tutorial#1]
The code for Lesson 4 uses this remove function
```
fun remove(item, items) {
  switch (items) {
     case []    -> []
     case x::xs -> if (item == x) xs
                   else x::remove(item, xs)
  }
}
```
that removes the first item that matches x.

Question 3 has the following text and answer

>   3.  What happens if you add multiple identical items to the todo list? What happens if you try to remove one of them? How could we change this behavior?
> 
> _Adding multiple items results in a todo list with repeated elements. If one of them is deleted, the others are too. Maybe the remove function could remove items based on their position, and the remove buttons could use item positions instead of their names when calling remove._

I suggest replacing the second sentence of the text in italics with 
> _If one of them is deleted, the first occurrence of that item is removed (regardless of whether it was the item selected). The remove function can be modified to remove every occurrence of an item but this is not a desirable solution either._

**Comment by jamescheney** [comment]
Sounds good to me.

**Comment by vcgalpin** [comment]
Done.
